name: Publish to NPM

on:
  push:
    branches:
      - main
  # optionally, you can publish only on tag releases
  # release:
  #   types: [created]

jobs:
  publish:
    name: Publish CLI to NPM
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: cli

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm i

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
